using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using ActiveSpaceSystem.Data;
using ActiveSpaceSystem.Models.enums;

namespace ActiveSpace.Models
{
    public class MonthlyContract
    {
        public string ContractRef { get; set; } = string.Empty;
        public string CustomerPhoneNumber { get; set; } = string.Empty;
        public string CourtRef { get; set; } = string.Empty;
        public string CourtName { get; set; } = string.Empty; // For UI compatibility
        public DateTime StartDate { get; set; } = DateTime.Today;
        public DateTime EndDate { get; set; } = DateTime.Today.AddMonths(1);
        public TimeSpan FixedStartTime { get; set; }
        public TimeSpan FixedEndTime { get; set; }
        public double MonthlyValue { get; set; }
        public string PaymentStatus { get; set; } = "معلق";

        // Backwards compatibility properties
        public string ContractID
        {
            get => ContractRef;
            set => ContractRef = value;
        }

        public string CustomerID
        {
            get => CustomerPhoneNumber;
            set => CustomerPhoneNumber = value;
        }

        public string CourtID
        {
            get => CourtRef;
            set => CourtRef = value;
        }

        public string DayOfWeek { get; set; } = string.Empty;
        public double PricePerHour { get; set; } = 50.0;
        public double Deposit { get; set; }

        public double TotalAmount
        {
            get => MonthlyValue;
            set => MonthlyValue = value;
        }

        public MonthlyContractStatus Status
        {
            get
            {
                if (PaymentStatus == "مدفوع") return MonthlyContractStatus.Active;
                return MonthlyContractStatus.Active; // Fallback
            }
            set
            {
                PaymentStatus = value == MonthlyContractStatus.Active ? "مدفوع" : "معلق";
            }
        }

        public Customer Customer
        {
            get => Customer.GetByPhone(CustomerPhoneNumber) ?? new Customer { FullName = "غير معروف" };
            set => CustomerPhoneNumber = value?.PhoneNumber ?? string.Empty;
        }

        public Court Court
        {
            get => Court.GetByRef(CourtRef) ?? Court.GetByRef(CourtName) ?? new Court { CourtName = "غير معروف" };
            set { 
                CourtRef = value?.CourtRef ?? string.Empty;
                CourtName = value?.CourtName ?? string.Empty;
            }
        }

        public List<BookingInventoryItem> InventoryItems { get; set; } = new List<BookingInventoryItem>();
        public List<Booking> Bookings { get; set; } = new List<Booking>();

        public void GenerateBookings()
        {
            Bookings.Clear();
            DateTime current = StartDate;
            double durationInHours = (FixedEndTime - FixedStartTime).TotalHours;

            // If DayOfWeek is empty, use the day of the week of StartDate
            string targetDay = string.IsNullOrEmpty(DayOfWeek) ? StartDate.DayOfWeek.ToString() : DayOfWeek;

            while (current <= EndDate)
            {
                if (current.DayOfWeek.ToString().Equals(targetDay, StringComparison.OrdinalIgnoreCase))
                {
                    double bookingAmount = durationInHours * PricePerHour;

                    var b = new Booking
                    {
                        BookingRef = "", // Will be generated by database
                        CustomerPhoneNumber = CustomerPhoneNumber,
                        CourtRef = CourtRef,
                        CourtName = CourtName,
                        ContractRef = ContractRef,
                        BookingDate = current,
                        StartTime = FixedStartTime,
                        EndTime = FixedEndTime,
                        Price = 0.0, // Contracts bookings are free, paid via contract monthly value
                        StatusString = "مؤكد"
                    };

                    b.InventoryItems = this.InventoryItems.Select(item => new BookingInventoryItem
                    {
                        ItemRef = item.ItemRef,
                        ItemName = item.ItemName,
                        Quantity = item.Quantity,
                        Price = item.Price,
                        UsageType = item.UsageType
                    }).ToList();

                    Bookings.Add(b);
                }
                current = current.AddDays(1);
            }
        }

        public static List<MonthlyContract> GetAll()
        {
            var list = new List<MonthlyContract>();
            using (var conn = DatabaseConnection.GetConnection())
            {
                conn.Open();
                string query = @"SELECT m.contract_ref, m.customer_phone_number, m.court_ref, m.start_date, m.end_date, m.start_time, m.end_time, m.monthly_value, m.payment_status, ISNULL(c.court_name, '') 
                                 FROM MONTHLY_CONTRACTS m LEFT JOIN COURTS c ON m.court_ref = c.court_ref";
                using (var cmd = new SqlCommand(query, conn))
                using (var reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var contract = new MonthlyContract
                        {
                            ContractRef = reader.GetString(0),
                            CustomerPhoneNumber = reader.GetString(1),
                            CourtRef = reader.GetString(2),
                            StartDate = reader.GetDateTime(3),
                            EndDate = reader.GetDateTime(4),
                            FixedStartTime = reader.GetTimeSpan(5),
                            FixedEndTime = reader.GetTimeSpan(6),
                            MonthlyValue = reader.IsDBNull(7) ? 0.0 : (double)reader.GetDecimal(7),
                            PaymentStatus = reader.GetString(8),
                            CourtName = reader.GetString(9)
                        };
                        contract.DayOfWeek = contract.StartDate.DayOfWeek.ToString();
                        list.Add(contract);
                    }
                }
            }
            return list;
        }

        public static MonthlyContract? GetByRef(string contractRef)
        {
            using (var conn = DatabaseConnection.GetConnection())
            {
                conn.Open();
                string query = @"SELECT m.contract_ref, m.customer_phone_number, m.court_ref, m.start_date, m.end_date, m.start_time, m.end_time, m.monthly_value, m.payment_status, ISNULL(c.court_name, '') 
                                 FROM MONTHLY_CONTRACTS m LEFT JOIN COURTS c ON m.court_ref = c.court_ref
                                 WHERE m.contract_ref = @ref";
                using (var cmd = new SqlCommand(query, conn))
                {
                    cmd.Parameters.AddWithValue("@ref", contractRef);
                    using (var reader = cmd.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            var contract = new MonthlyContract
                            {
                                ContractRef = reader.GetString(0),
                                CustomerPhoneNumber = reader.GetString(1),
                                CourtRef = reader.GetString(2),
                                StartDate = reader.GetDateTime(3),
                                EndDate = reader.GetDateTime(4),
                                FixedStartTime = reader.GetTimeSpan(5),
                                FixedEndTime = reader.GetTimeSpan(6),
                                MonthlyValue = reader.IsDBNull(7) ? 0.0 : (double)reader.GetDecimal(7),
                                PaymentStatus = reader.GetString(8),
                                CourtName = reader.GetString(9)
                            };
                            contract.DayOfWeek = contract.StartDate.DayOfWeek.ToString();
                            return contract;
                        }
                    }
                }
            }
            return null;
        }

        public void Save()
        {
            using (var conn = DatabaseConnection.GetConnection())
            {
                conn.Open();
                string checkQuery = "SELECT COUNT(*) FROM MONTHLY_CONTRACTS WHERE contract_ref = @ref";
                bool exists = false;
                using (var checkCmd = new SqlCommand(checkQuery, conn))
                {
                    checkCmd.Parameters.AddWithValue("@ref", this.ContractRef);
                    exists = (int)checkCmd.ExecuteScalar() > 0;
                }

                if (exists)
                {
                    string updateQuery = @"
                        UPDATE MONTHLY_CONTRACTS 
                        SET customer_phone_number = @cust_phone, court_ref = @court_ref, 
                            start_date = @start_date, end_date = @end_date, 
                            start_time = @start_time, end_time = @end_time, 
                            monthly_value = @val, payment_status = @status 
                        WHERE contract_ref = @ref";
                    using (var cmd = new SqlCommand(updateQuery, conn))
                    {
                        cmd.Parameters.AddWithValue("@ref", this.ContractRef);
                        cmd.Parameters.AddWithValue("@cust_phone", this.CustomerPhoneNumber);
                        cmd.Parameters.AddWithValue("@court_ref", this.CourtRef);
                        cmd.Parameters.AddWithValue("@start_date", this.StartDate);
                        cmd.Parameters.AddWithValue("@end_date", this.EndDate);
                        cmd.Parameters.AddWithValue("@start_time", this.FixedStartTime);
                        cmd.Parameters.AddWithValue("@end_time", this.FixedEndTime);
                        cmd.Parameters.AddWithValue("@val", this.MonthlyValue);
                        cmd.Parameters.AddWithValue("@status", this.PaymentStatus);
                        cmd.ExecuteNonQuery();
                    }
                }
                else
                {
                    // Generate a ref if empty (using gap-filling logic to reuse deleted IDs)
                    if (string.IsNullOrEmpty(this.ContractRef))
                    {
                        var existingRefs = new HashSet<int>();
                        string selectQuery = "SELECT CAST(RIGHT(contract_ref, 3) AS INT) FROM MONTHLY_CONTRACTS WHERE contract_ref LIKE 'CONT-%'";
                        using (var selectCmd = new SqlCommand(selectQuery, conn))
                        using (var reader = selectCmd.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                if (!reader.IsDBNull(0))
                                {
                                    existingRefs.Add(reader.GetInt32(0));
                                }
                            }
                        }

                        int nextSeq = 1;
                        while (existingRefs.Contains(nextSeq))
                        {
                            nextSeq++;
                        }
                        this.ContractRef = "CONT-" + nextSeq.ToString("D3");
                    }

                    string insertQuery = @"
                        INSERT INTO MONTHLY_CONTRACTS (contract_ref, customer_phone_number, court_ref, start_date, end_date, start_time, end_time, monthly_value, payment_status) 
                        VALUES (@ref, @cust_phone, @court_ref, @start_date, @end_date, @start_time, @end_time, @val, @status)";
                    using (var cmd = new SqlCommand(insertQuery, conn))
                    {
                        cmd.Parameters.AddWithValue("@ref", this.ContractRef);
                        cmd.Parameters.AddWithValue("@cust_phone", this.CustomerPhoneNumber);
                        cmd.Parameters.AddWithValue("@court_ref", this.CourtRef);
                        cmd.Parameters.AddWithValue("@start_date", this.StartDate);
                        cmd.Parameters.AddWithValue("@end_date", this.EndDate);
                        cmd.Parameters.AddWithValue("@start_time", this.FixedStartTime);
                        cmd.Parameters.AddWithValue("@end_time", this.FixedEndTime);
                        cmd.Parameters.AddWithValue("@val", this.MonthlyValue);
                        cmd.Parameters.AddWithValue("@status", this.PaymentStatus);
                        cmd.ExecuteNonQuery();
                    }

                    // For new contracts, generate and save the bookings to database!
                    this.GenerateBookings();
                    foreach (var booking in this.Bookings)
                    {
                        booking.ContractRef = this.ContractRef;
                        booking.Save();
                    }
                }
            }
        }

        public static void Delete(string contractRef)
        {
            using (var conn = DatabaseConnection.GetConnection())
            {
                conn.Open();

                // 1. Delete payments linked to bookings of this contract
                string deleteBookingPayments = "DELETE FROM PAYMENTS WHERE booking_ref IN (SELECT booking_ref FROM BOOKINGS WHERE contract_ref = @ref)";
                using (var cmd = new SqlCommand(deleteBookingPayments, conn))
                {
                    cmd.Parameters.AddWithValue("@ref", contractRef);
                    cmd.ExecuteNonQuery();
                }

                // 2. Delete payments linked directly to this contract
                string deleteContractPayments = "DELETE FROM PAYMENTS WHERE contract_ref = @ref";
                using (var cmd = new SqlCommand(deleteContractPayments, conn))
                {
                    cmd.Parameters.AddWithValue("@ref", contractRef);
                    cmd.ExecuteNonQuery();
                }

                // 3. Delete related bookings
                string deleteBookings = "DELETE FROM BOOKINGS WHERE contract_ref = @ref";
                using (var cmd = new SqlCommand(deleteBookings, conn))
                {
                    cmd.Parameters.AddWithValue("@ref", contractRef);
                    cmd.ExecuteNonQuery();
                }

                // 4. Delete the contract itself
                string deleteContract = "DELETE FROM MONTHLY_CONTRACTS WHERE contract_ref = @ref";
                using (var cmd = new SqlCommand(deleteContract, conn))
                {
                    cmd.Parameters.AddWithValue("@ref", contractRef);
                    cmd.ExecuteNonQuery();
                }
            }
        }
    }
}